# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo_Base_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_full_name', models.CharField(max_length=255)),
                ('fork_count', models.IntegerField(max_length=11)),
                ('star_count', models.IntegerField(max_length=11)),
                ('subscribe_count', models.IntegerField(max_length=11)),
            ],
        ),
    ]
