# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_base_info',
            name='fork_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repo_base_info',
            name='star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repo_base_info',
            name='subscribe_count',
            field=models.IntegerField(default=0),
        ),
    ]
