# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20180922_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo_Owner_Info',
            fields=[
                ('owner_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=500)),
                ('follows_count', models.IntegerField(default=0)),
                ('owner_type', models.IntegerField(default=0)),
                ('repos_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='repo_base_info',
            name='repo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repo_base_info',
            name='repo_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='github.Repo_Owner_Info'),
        ),
    ]
