# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-23 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20180923_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo_Develop_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commit_count', models.IntegerField(default=0)),
                ('command_count', models.IntegerField(default=0)),
                ('issue_count', models.IntegerField(default=0)),
                ('issue_count_permonth', models.IntegerField(default=0)),
                ('issue_command_count', models.IntegerField(default=0)),
                ('issue_command_count_permonth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repo_Developer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Repo_Issue_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_user_type', models.IntegerField(default=0)),
                ('issue_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Org_Info',
            fields=[
                ('user_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=500)),
                ('follows_count', models.IntegerField(default=0)),
                ('repos_count', models.IntegerField(default=1)),
                ('blog_url', models.CharField(max_length=500)),
                ('emall_url', models.CharField(max_length=500)),
                ('belong_org', models.IntegerField(default=0)),
                ('org_member_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='repo_base_info',
            name='id',
        ),
        migrations.AddField(
            model_name='repo_base_info',
            name='owner_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repo_base_info',
            name='repo_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repo_base_info',
            name='repo_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repo_base_info',
            name='repo_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='github.User_Org_Info'),
        ),
        migrations.DeleteModel(
            name='Repo_Owner_Info',
        ),
        migrations.AddField(
            model_name='repo_issue_info',
            name='repo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.Repo_Base_Info'),
        ),
        migrations.AddField(
            model_name='repo_issue_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.User_Org_Info'),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='repo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.Repo_Base_Info'),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.User_Org_Info'),
        ),
        migrations.AddField(
            model_name='repo_develop_info',
            name='repo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.Repo_Base_Info'),
        ),
    ]
