# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_auto_20180923_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo_base_info',
            name='language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_base_info',
            name='repo_created_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repo_base_info',
            name='repo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_develop_info',
            name='code_add_count_perweek',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_develop_info',
            name='code_delete_count_perweek',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_develop_info',
            name='command_count_permonth',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_develop_info',
            name='commit_count_perweek_lastyear',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='user_add_count_perweek',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='user_commit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='user_commit_count_perweek',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='user_creat_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='user_del_count_perweek',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='user_last_update_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repo_issue_info',
            name='issue_close_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='repo_issue_info',
            name='issue_create_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
