# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_auto_20180924_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Members_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='user_org_info',
            old_name='emall_url',
            new_name='email_url',
        ),
        migrations.RenameField(
            model_name='user_org_info',
            old_name='create_time',
            new_name='user_create_time',
        ),
        migrations.AddField(
            model_name='repo_base_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repo_develop_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repo_developer_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repo_issue_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_org_info',
            name='user_update_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_org_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='org_members_info',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.User_Org_Info'),
        ),
    ]
