# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0008_auto_20180925_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo_base_info',
            name='repo_update_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
