# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0009_repo_base_info_repo_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo_base_info',
            name='collaborators_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_org_info',
            name='user_fullname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
