# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0012_auto_20181002_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_org_info',
            name='user_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
