# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0014_auto_20181009_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_develop_info',
            old_name='Commit_count',
            new_name='commit_count',
        ),
        migrations.AddField(
            model_name='repo_develop_info',
            name='commit_count_permonth',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repo_issue_info',
            name='issue_update_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
