# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0015_auto_20181009_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_issue_info',
            name='issue_user_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
