# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0016_auto_20181009_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_issue_info',
            name='issue_close_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issue_info',
            name='issue_create_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_issue_info',
            name='issue_update_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_milestones_info',
            name='milestones_close_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_milestones_info',
            name='milestones_create_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_milestones_info',
            name='milestones_update_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_pulls_info',
            name='pull_closed_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_pulls_info',
            name='pull_created_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_pulls_info',
            name='pull_merged_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo_pulls_info',
            name='pull_update_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
