# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0017_auto_20181009_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_org_info',
            name='belong_org',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_org_info',
            name='blog_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_org_info',
            name='email_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
