# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0018_auto_20181009_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_pulls_info',
            old_name='pull_closed_at',
            new_name='pull_closed_time',
        ),
        migrations.RenameField(
            model_name='repo_pulls_info',
            old_name='pull_created_at',
            new_name='pull_create_time',
        ),
        migrations.RenameField(
            model_name='repo_pulls_info',
            old_name='pull_merged_at',
            new_name='pull_merged_time',
        ),
        migrations.RenameField(
            model_name='repo_pulls_info',
            old_name='pull_update_at',
            new_name='pull_update_time',
        ),
        migrations.RemoveField(
            model_name='repo_pulls_info',
            name='pull_add_count',
        ),
        migrations.RemoveField(
            model_name='repo_pulls_info',
            name='pull_changed_files',
        ),
        migrations.RemoveField(
            model_name='repo_pulls_info',
            name='pull_commit_count',
        ),
        migrations.RemoveField(
            model_name='repo_pulls_info',
            name='pull_del_count',
        ),
    ]
