# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0019_auto_20181009_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo_pulls_info',
            old_name='pull_user',
            new_name='user',
        ),
    ]
