# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0020_auto_20181009_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_base_info',
            name='owner_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
